services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    shm_size: 10GB
    command: 
      - 'postgres'
      - '-c'
      - 'config_file=/etc/postgresql/postgresql.conf'
    environment:
      POSTGRES_DB: tpcds 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - $PWD/conf/postgres/tpcds.conf:/etc/postgresql/postgresql.conf
      - $PWD/data/postgres:/var/lib/postgresql/data
      - $PWD/kept/postgres/scripts:/scripts
      - $PWD/kept/postgres/ddls:/tpcds/ddls
      - $PWD/shared/data:/tpcds/data 
      - $PWD/shared/postgres/queries:/tpcds/queries
  workdesk:
    container_name: workdesk
    image: ubuntu:focal
    tty: true
    volumes:
      - $PWD/files:/works
      - $PWD/shared:/shared
      - $PWD/kept:/kept

