CONNECT sys/oraclepw@ORCLPDB1 as sysdba;
CREATE USER demouser IDENTIFIED BY demopswd;
ALTER USER demouser quota unlimited on USERS;

GRANT CREATE SESSION TO demouser ;
GRANT SET CONTAINER TO demouser ;
GRANT SELECT ON V_$DATABASE TO demouser ;
GRANT FLASHBACK ANY TABLE TO demouser ;
GRANT SELECT ANY TABLE TO demouser ;
GRANT SELECT_CATALOG_ROLE TO demouser ;
GRANT EXECUTE_CATALOG_ROLE TO demouser ;
GRANT SELECT ANY TRANSACTION TO demouser ;
GRANT SELECT ANY DICTIONARY TO demouser ;
GRANT LOGMINING TO demouser ;

GRANT CREATE TABLE TO demouser ;
GRANT LOCK ANY TABLE TO demouser ;
GRANT CREATE SEQUENCE TO demouser ;

GRANT EXECUTE ON DBMS_LOGMNR TO demouser ;
GRANT EXECUTE ON DBMS_LOGMNR_D TO demouser ;

GRANT SELECT ON V_$LOG TO demouser ;
GRANT SELECT ON V_$LOG_HISTORY TO demouser ;
GRANT SELECT ON V_$LOGMNR_LOGS TO demouser ;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO demouser ;
GRANT SELECT ON V_$LOGMNR_PARAMETERS TO demouser ;
GRANT SELECT ON V_$LOGFILE TO demouser ;
GRANT SELECT ON V_$ARCHIVED_LOG TO demouser ;
GRANT SELECT ON V_$ARCHIVE_DEST_STATUS TO demouser ;
GRANT SELECT ON V_$TRANSACTION TO demouser ;

EXIT;